import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { EstimateRecord } from "@/hooks/useEstimates";

export function generateEstimatePDF(estimate: EstimateRecord, partnerName: string) {
  const doc = new jsPDF();
  const lineItems = (estimate.line_items || []) as any[];

  // Header with branding
  autoTable(doc, {
    body: [
      [
        {
          content: "NOCH Power",
          styles: { halign: "left", fontSize: 18, textColor: "#1e293b", fontStyle: "bold" },
        },
        {
          content: "SERVICE ESTIMATE",
          styles: { halign: "right", fontSize: 18, textColor: "#25b3a5", fontStyle: "bold" },
        },
      ],
    ],
    theme: "plain",
    styles: { cellPadding: { top: 5, bottom: 5, left: 10, right: 10 } },
  });

  // Estimate info
  const statusLabel = estimate.status.charAt(0).toUpperCase() + estimate.status.slice(1);
  autoTable(doc, {
    body: [
      [
        { content: `Ticket #: ${estimate.ticket_id || "—"}`, styles: { fontSize: 10 } },
        { content: `Station: ${estimate.station_id || "—"}`, styles: { fontSize: 10 } },
      ],
      [
        { content: `Site: ${estimate.site_name || "—"}`, styles: { fontSize: 10 } },
        { content: `Partner: ${partnerName}`, styles: { fontSize: 10 } },
      ],
      [
        { content: `Customer: ${estimate.customer_email || "—"}`, styles: { fontSize: 10 } },
        { content: `Account Manager: ${estimate.account_manager || "—"}`, styles: { fontSize: 10 } },
      ],
      [
        { content: `Status: ${statusLabel}`, styles: { fontSize: 10, fontStyle: "bold" } },
        {
          content: `Date: ${new Date(estimate.created_at).toLocaleDateString()}`,
          styles: { fontSize: 10 },
        },
      ],
    ],
    theme: "plain",
    styles: { cellPadding: { top: 2, bottom: 2, left: 10, right: 10 } },
  });

  // Line items table
  autoTable(doc, {
    head: [["Description", "Qty", "Unit", "Rate", "Amount"]],
    body: lineItems.map((item: any) => [
      item.description || "",
      String(item.qty),
      item.unit || "",
      `$${Number(item.rate).toFixed(2)}`,
      `$${Number(item.amount).toFixed(2)}`,
    ]),
    startY: (doc as any).lastAutoTable?.finalY
      ? (doc as any).lastAutoTable.finalY + 10
      : 80,
    headStyles: {
      fillColor: [37, 179, 165],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 10,
    },
    bodyStyles: { fontSize: 10 },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { halign: "right", cellWidth: 20 },
      2: { cellWidth: 25 },
      3: { halign: "right", cellWidth: 30 },
      4: { halign: "right", cellWidth: 30 },
    },
    styles: { cellPadding: { top: 3, bottom: 3, left: 5, right: 5 } },
  });

  // Totals
  const finalY = (doc as any).lastAutoTable?.finalY || 140;
  autoTable(doc, {
    body: [
      [
        { content: "", styles: { cellWidth: "auto" } },
        { content: "Subtotal", styles: { halign: "right", fontStyle: "bold", fontSize: 10 } },
        {
          content: `$${Number(estimate.subtotal).toFixed(2)}`,
          styles: { halign: "right", fontSize: 10 },
        },
      ],
      [
        { content: "" },
        {
          content: `Tax (${(Number(estimate.tax_rate) * 100).toFixed(0)}%)`,
          styles: { halign: "right", fontStyle: "bold", fontSize: 10 },
        },
        {
          content: `$${Number(estimate.tax).toFixed(2)}`,
          styles: { halign: "right", fontSize: 10 },
        },
      ],
      [
        { content: "" },
        {
          content: "TOTAL",
          styles: { halign: "right", fontStyle: "bold", fontSize: 12, textColor: "#25b3a5" },
        },
        {
          content: `$${Number(estimate.total).toFixed(2)}`,
          styles: { halign: "right", fontStyle: "bold", fontSize: 12, textColor: "#25b3a5" },
        },
      ],
    ],
    startY: finalY + 5,
    theme: "plain",
    styles: { cellPadding: { top: 2, bottom: 2, left: 5, right: 5 } },
  });

  // Notes
  if (estimate.notes) {
    const notesY = (doc as any).lastAutoTable?.finalY || finalY + 40;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Notes:", 14, notesY + 10);
    doc.setFont("helvetica", "normal");
    const splitNotes = doc.splitTextToSize(estimate.notes, 180);
    doc.text(splitNotes, 14, notesY + 16);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by NOCH Power Platform", 14, pageHeight - 10);
  doc.text(new Date().toLocaleString(), 200 - 14, pageHeight - 10, { align: "right" });

  return doc;
}

export function downloadEstimatePDF(estimate: EstimateRecord, partnerName: string) {
  const doc = generateEstimatePDF(estimate, partnerName);
  const station = (estimate.station_id || estimate.site_name || "Unknown").replace(/[^a-zA-Z0-9-_]/g, "_");
  const ticket = (estimate.ticket_id || "NoTicket").replace(/[^a-zA-Z0-9-_]/g, "_");
  const partner = (partnerName || "NoPartner").replace(/[^a-zA-Z0-9-_]/g, "_");
  const filename = `${station}_${ticket}_${partner}.pdf`;
  doc.save(filename);
}

export function downloadMultipleEstimatePDFs(estimates: EstimateRecord[], partnerName: string) {
  estimates.forEach((est) => {
    downloadEstimatePDF(est, partnerName);
  });
}
