import { useState } from "react";
import { Inbox, FileCheck, ChevronRight } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { BusinessPageHeader } from "@/components/business/BusinessPageHeader";
import { NeuralOsBadge } from "@/components/business/NeuralOsBadge";
import Submissions from "@/pages/Submissions";
import NochPlusAssessments from "@/pages/placeholders/NochPlusAssessments";

const PIPELINE_STAGES = [
  "Submission", "AI Triage", "Ticket", "Estimate", "Work Order", "Field Report", "Assessment",
];

function StatusChain() {
  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-center gap-1 text-xs flex-wrap">
          <span className="text-muted-foreground mr-2 font-medium uppercase tracking-wider">Submission lifecycle:</span>
          {PIPELINE_STAGES.map((stage, i) => (
            <span key={stage} className="flex items-center gap-1">
              <span className="px-2 py-0.5 rounded-full bg-muted text-foreground/80">{stage}</span>
              {i < PIPELINE_STAGES.length - 1 && <ChevronRight className="h-3 w-3 text-muted-foreground" />}
            </span>
          ))}
        </div>
        <p className="text-[11px] text-muted-foreground mt-2 flex items-center gap-2">
          <NeuralOsBadge /> AI triage runs automatically on every submission before a ticket is created.
        </p>
      </CardContent>
    </Card>
  );
}

export default function BusinessSubmissions() {
  const [tab, setTab] = useState("submissions");

  return (
    <div className="p-6 space-y-6">
      <BusinessPageHeader
        title="Submissions"
        subtitle="Customer-portal intake. Site assessments and repair requests flowing into Neural OS for triage."
        icon={Inbox}
      />

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList>
          <TabsTrigger value="submissions" className="gap-1.5"><Inbox className="h-3.5 w-3.5" />Submissions</TabsTrigger>
          <TabsTrigger value="assessments" className="gap-1.5"><FileCheck className="h-3.5 w-3.5" />Assessments</TabsTrigger>
        </TabsList>

        <TabsContent value="submissions" className="mt-6 space-y-4">
          <StatusChain />
          <Card>
            <CardContent className="p-0">
              <Submissions />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="assessments" className="mt-6 space-y-4">
          <p className="text-xs text-muted-foreground flex items-center gap-2">
            <NeuralOsBadge label="generated by neural os" />
            All reports are AI-compiled from submission photos and site data.
          </p>
          <Card>
            <CardContent className="p-0">
              <NochPlusAssessments />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
