import { Brain } from "lucide-react";
import { cn } from "@/lib/utils";

interface NeuralOsBadgeProps {
  /** Optional confidence percentage to render as "· 92%" */
  confidence?: number;
  /** Override label, e.g. "generated by neural os" */
  label?: string;
  className?: string;
}

/**
 * Subtle attribution pill for AI-generated artifacts.
 * Per locked decision #4 in the Neural Deck briefing — small, lowercase,
 * muted teal styling, similar weight to existing status pills.
 */
export function NeuralOsBadge({ confidence, label, className }: NeuralOsBadgeProps) {
  const text = label
    ? label
    : confidence !== undefined
      ? `triaged by neural os · ${Math.round(confidence)}%`
      : "neural os";

  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full border border-teal-500/30 bg-teal-500/10",
        "px-1.5 py-0.5 text-[10px] font-medium lowercase text-teal-700 dark:text-teal-300",
        className,
      )}
    >
      <Brain className="h-2.5 w-2.5" />
      <span className="tracking-wide">{text}</span>
    </span>
  );
}
